language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-28.0.1 
        - android-27

        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services

        - addon-google_apis-google-27
        - addon-google_apis-google-19
        - sys-img-x86-google_apis-27
        - sys-img-x86-google_apis-19
